// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resume.proto

package ru.itis.hhserver.gprc;

public final class Resume {
  private Resume() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResumeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResumeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SingleResumeResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SingleResumeResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ResumeListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ResumeListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\014resume.proto\"1\n\rResumeRequest\022\024\n\007sorti" +
      "ng\030\001 \001(\tH\000\210\001\001B\n\n\010_sorting\"\217\001\n\024SingleResu" +
      "meResponse\022\r\n\005title\030\001 \001(\t\022\023\n\013description" +
      "\030\002 \001(\t\022\014\n\004link\030\003 \001(\t\022\020\n\010location\030\004 \001(\t\022\016" +
      "\n\006salary\030\005 \001(\t\022\022\n\nexperience\030\006 \001(\t\022\017\n\007co" +
      "mpany\030\007 \001(\t\"9\n\022ResumeListResponse\022#\n\004lis" +
      "t\030\001 \003(\0132\025.SingleResumeResponse2I\n\rResume" +
      "Service\0228\n\rgetResumeList\022\016.ResumeRequest" +
      "\032\023.ResumeListResponse(\0010\001B\034\n\030ru.itis.hha" +
      "gregator.gprcP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ResumeRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ResumeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResumeRequest_descriptor,
        new String[] { "Sorting", "Sorting", });
    internal_static_SingleResumeResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SingleResumeResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SingleResumeResponse_descriptor,
        new String[] { "Title", "Description", "Link", "Location", "Salary", "Experience", "Company", });
    internal_static_ResumeListResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ResumeListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ResumeListResponse_descriptor,
        new String[] { "List", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
