// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resume.proto

package ru.itis.hhclient.gprc;

public interface ResumeListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ResumeListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .SingleResumeResponse list = 1;</code>
   */
  java.util.List<SingleResumeResponse>
      getListList();
  /**
   * <code>repeated .SingleResumeResponse list = 1;</code>
   */
  SingleResumeResponse getList(int index);
  /**
   * <code>repeated .SingleResumeResponse list = 1;</code>
   */
  int getListCount();
  /**
   * <code>repeated .SingleResumeResponse list = 1;</code>
   */
  java.util.List<? extends SingleResumeResponseOrBuilder>
      getListOrBuilderList();
  /**
   * <code>repeated .SingleResumeResponse list = 1;</code>
   */
  SingleResumeResponseOrBuilder getListOrBuilder(
      int index);
}
