// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resume.proto

package ru.itis.hhclient.gprc;

public interface SingleResumeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SingleResumeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string title = 1;</code>
   * @return The title.
   */
  String getTitle();
  /**
   * <code>string title = 1;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string description = 2;</code>
   * @return The description.
   */
  String getDescription();
  /**
   * <code>string description = 2;</code>
   * @return The bytes for description.
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>string link = 3;</code>
   * @return The link.
   */
  String getLink();
  /**
   * <code>string link = 3;</code>
   * @return The bytes for link.
   */
  com.google.protobuf.ByteString
      getLinkBytes();

  /**
   * <code>string location = 4;</code>
   * @return The location.
   */
  String getLocation();
  /**
   * <code>string location = 4;</code>
   * @return The bytes for location.
   */
  com.google.protobuf.ByteString
      getLocationBytes();

  /**
   * <code>string salary = 5;</code>
   * @return The salary.
   */
  String getSalary();
  /**
   * <code>string salary = 5;</code>
   * @return The bytes for salary.
   */
  com.google.protobuf.ByteString
      getSalaryBytes();

  /**
   * <code>string experience = 6;</code>
   * @return The experience.
   */
  String getExperience();
  /**
   * <code>string experience = 6;</code>
   * @return The bytes for experience.
   */
  com.google.protobuf.ByteString
      getExperienceBytes();

  /**
   * <code>string company = 7;</code>
   * @return The company.
   */
  String getCompany();
  /**
   * <code>string company = 7;</code>
   * @return The bytes for company.
   */
  com.google.protobuf.ByteString
      getCompanyBytes();
}
